redis_host = 'redis-18815.c300.eu-central-1-1.ec2.cloud.redislabs.com'
redis_password = 'JexSl4Sog5ir4Uw2byUmSe4HcunzkyKr'

SECRET_KEY = 'd06042be4bd95ed4a7705199c54beb3bd21fd621f9fcfc321dadde2e6816eca1'